# Provisionning partiel du serveur

- name: "FIX: Ubuntu 16.04 LTS doesn't come with certain modules, required by ansible"
  raw: apt-get install python-minimal aptitude -y
  become: true
  become_user: root
  become_method: sudo

- name: Update the package repositories
  apt:
    update_cache=yes
    upgrade=safe
    cache_valid_time=3600

- name: Set the hostname
  hostname: name={{ hostname }}
  when: hostname|default(False) != False

- name: Configure the locale
  lineinfile:
    dest=/etc/environment
    regexp='^LC_ALL='
    line='LC_ALL=en_US.UTF-8'

- name: Generate the locale
  command: locale-gen en_US.UTF-8
  register: command_result
  changed_when: "'done' in command_result.stdout"

- name: Authorize the Vagrant key to connect as the web user
  command: sudo cp .ssh/authorized_keys ~{{ web_user }}/.ssh/
  when: vagrant|default(False)

- name: Ensure GIT, libs and co. are installed
  apt:
    name={{ item }}
    state=latest
  with_items: "{{apt_packages}}"
