---

- name: Change initial working directory
  lineinfile:
    path: /home/vagrant/.profile
    line: 'cd /vagrant'

- name: Install the project - JS dependencies
  shell: "yarn install --silent"
  ignore_errors: yes # Somewhat running Yarn fails Ansible randomly
  args:
      chdir: "/vagrant"
